# Generated by Django 5.2.14 on 2026-09-04 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical Skill'), ('SOFT', 'Soft Skill'), ('DOMAIN', 'Domain Knowledge')], default='TECHNICAL', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Student / Candidate'), ('INDUSTRY', 'Industry Partner / Recruiter'), ('ACADEMIA', 'Academia / Placement Officer')], default='STUDENT', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('institution_or_company', models.CharField(blank=True, default='', max_length=150)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('designation', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='Delhi, India', max_length=100)),
                ('avatar_url', models.CharField(blank=True, default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='Comma-separated skills/technologies', max_length=200)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portal.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.CharField(blank=True, default='https://cdn-icons-png.flaticon.com/512/2991/2991148.png', max_length=255)),
                ('opportunity_type', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('FULL_TIME', 'Placement / Full Time'), ('PROJECT', 'Industry Research Project')], default='INTERNSHIP', max_length=20)),
                ('location', models.CharField(default='Remote / Hybrid', max_length=100)),
                ('stipend_or_salary', models.CharField(default='₹45,000 / month', max_length=100)),
                ('description', models.TextField()),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=7.5, max_digits=4)),
                ('deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required_skills', models.ManyToManyField(related_name='job_requirements', to='portal.skill')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='portal.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('issuer', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='portal.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('date_awarded', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='portal.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(default='B.Tech Computer Science', max_length=100)),
                ('cgpa', models.DecimalField(decimal_places=2, default=8.76, max_digits=4)),
                ('max_cgpa', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('passing_year', models.IntegerField(default=2026)),
                ('completed_internships_count', models.IntegerField(default=2)),
                ('earned_achievements_count', models.IntegerField(default=8)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_record', to='portal.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_percentage', models.IntegerField(default=80)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='ADVANCED', max_length=20)),
                ('verified_by_academia', models.BooleanField(default=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.skill')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='portal.userprofile')),
            ],
            options={
                'unique_together': {('profile', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW', 'Interview Scheduled'), ('ACCEPTED', 'Accepted / Offered'), ('REJECTED', 'Not Shortlisted')], default='APPLIED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('cover_note', models.TextField(blank=True, default='')),
                ('recruiter_notes', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='portal.internshipjob')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.userprofile')),
            ],
            options={
                'unique_together': {('student', 'job')},
            },
        ),
    ]
