# Generated by Django 5.2.14 on 2026-09-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='branch_and_year',
            field=models.CharField(blank=True, default='B.Tech CSE • 4th Year', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_url',
            field=models.CharField(blank=True, default='https://github.com/ananyasharma', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.CharField(blank=True, default='https://linkedin.com/in/ananyasharma', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='Passionate Computer Science student specializing in Full-Stack Development and AI Systems.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='Computer Science & Engineering', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='institution_or_company',
            field=models.CharField(blank=True, default='Delhi Technological University', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='+91 98765 43210', max_length=20),
        ),
    ]
